<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Product;
use Knp\Component\Pager\PaginatorInterface;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var PaginatorInterface
     */
    private $paginator;

    public function setPaginator(PaginatorInterface $paginator)
    {
        $this->paginator = $paginator;
    }

    public function getPaginatedProducts($pageNumber, $limitPerPage)
    {
        if($this->paginator === null) {
            throw new \Exception("This method requires paginator to be setted.");
        }

        $qb = $this->_em->createQueryBuilder();

        $qb->from(Product::class, 'p')
            ->select('p');

        $query = $qb->getQuery();

        return $this->paginator->paginate($query, $pageNumber, $limitPerPage);
    }
}
